sudo:
    false

language: 
    node_js

node_js:
    - '13'

cache:
    directories:
        - ./app/server/node_modules

before_install:
    - cd ./app/server
    # - sudo apt-get install -y libxml2-dev
    
install:
    - npm ci

script:
    # - npm run lint
    - npm run test-ci

after_success: 
    - coveralls

notifications:
    email: false