sudo:
    false

language: 
    node_js

node_js:
    - '13'

# dist: 
#     trusty
    
# service:
#     mongodb

# env:
#     - NODE_ENV=ci PORT=5000

cache:
    directories:
        - node_modules

# before_install:
#     - sudo apt-get install -y libxml2-dev
    
install:
    - npm --prefix ./app/server ci

script:
    - npm run test-ci